"""Generated by SimForge GPU MVP. Review reports before execution."""
# WARNING: Partial conversion. Review unsupported_report.md before execution.

"""Bootstrap mean CPU fixture."""

import cupy as cp


def run(n_resamples: int = 1000) -> float:
    data = cp.array([1.0, 2.0, 3.0, 4.0, 5.0])
    estimates = []
    for _ in range(n_resamples):
        indices = cp.random.uniform(size=len(data))
        selected = data[(indices * len(data)).astype(int)]
        estimates.append(cp.mean(selected))
    return float(cp.mean(estimates))


if __name__ == "__main__":
    print(run())
