"""Generated by SimForge GPU MVP. Review reports before execution."""

"""Normal mean probability CPU fixture."""

import cupy as cp


def run(n_samples: int = 10000) -> float:
    draws = cp.random.normal(loc=0.0, scale=1.0, size=n_samples)
    return float(cp.mean(draws > 1.96))


if __name__ == "__main__":
    print(run())
