"""Generated by SimForge GPU MVP. Review reports before execution."""

"""Random walk CPU fixture."""

import cupy as cp


def run(n_steps: int = 1000) -> float:
    steps = cp.random.binomial(1, 0.5, size=n_steps)
    signed_steps = cp.maximum(steps * 2 - 1, -1)
    return float(cp.sum(signed_steps))


if __name__ == "__main__":
    print(run())
